### PR TITLE
feat: update to Reflex 6.4 and sdl 2.5.0.0

### PR DESCRIPTION
**Pull request by michivi**
Hi,

I had to upgrade the dependencies' versions for a personal project. More specifically, this version is compatible with Reflex 6.4 and Haskell SDL2 2.5. Also added support for Nix through Stack.
It compiles fine and works with GHC 8.6.5. I haven't done any test on other versions. However, I'm sharing it, hoping it can prove useful!

Have a nice day!

### CODE REVIEW

**Review by schell — APPROVED** [review]
Thank you!

**Comment by o1lo01ol1o** [comment]
Hi, What's the status on this?

**Comment by schell** [comment]
Merged!

**Comment by schell** [comment]
@o1lo01ol1o - sorry for the hold up, it seems I just dropped it on the floor :(

**Pull request merged**
